grafana:
  adminUser: admin
  adminPassword: admin

  service:
    type: NodePort
    nodePort: 30030

  ingress:
    enabled: false

prometheus:
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  service:
    type: NodePort
    nodePort: 30091
