apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
  type: {{ .Values.service.type }}
