apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - name: postgres
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5432
  - name: metrics
    protocol: TCP
    port: 9187
    targetPort: 9187

